spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://my-rev-db.cjtgqrath0m4.us-east-1.rds.amazonaws.com:5432/postgres?currentSchema=feastfreedom
        username: CCrawford
        password: A3s83jf7SAf1
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    session:
        store-type: jdbc
        timeout: 600
        jdbc:
            initialize-schema: always

server:
    port: 8090